[pytest]
testpaths = pytests_atypier
pythonpath = . heavy_machinery heavy_machinery/cleaning_phase heavy_machinery/modelling_phase
filterwarnings =
    ignore::PendingDeprecationWarning:seaborn.categorical
    ignore::ResourceWarning
